t-rds-xtrabackup-80:
  pkgpara:
  machine:
    docker:
      el6: rpmbuild6u2
      alios7:
        x86_64: rpmbuild7u2
        aarch64: alibase/alios7u2-admin-2916-4.19.48-006.ali4000.alios7.aarch64  # GCC 9.2
t-rds-xcluster-xtrabackup-80:
  pkgpara:
    DOCKER: 1
t-rds-galaxyengine-xtrabackup-80:
  pkgpara:
    DOCKER: 1
t-polardb-x-xtrabackup-opensource:
  pkgpara:
    DOCKER: 1
